# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt

COPY hello.py .

CMD python hello.py

# docker build -t hello . # Tout sauf CMD
# docker run hello # CMD
# Ajouter -f Dockerfile.hello si le fichier ne s'appel pas Dockerfile uniquement pour le build