version: '3.1'
services:
  sklearn_api:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./logs:/app/logs:rw

  tf_api:
    build:
      context: .
      dockerfile: ./Dockerfile.tf
    ports:
      - 5001:5001

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - wsgi
    restart: always
    ports:
      - 80:80

  wsgi:
    build:
      context: .
      dockerfile: ./Dockerfile.wsgi
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./logs/wsgi:/app/logs:rw
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M

  nginx_and_wsgi:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx.wsgi
    restart: always
    ports:
      - 81:80
    volumes:
      - ./logs/nginx_wsgi:/app/logs:rw






