version: '3.1'
services:
  sklearn_api:
    build:
      context: .
    ports:
      - 5000:5000

  tf_api:
    build:
      context: .
      dockerfile: ./Dockerfile.tf
    ports:
      - 5001:5001

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    restart: always
    ports:
      - 80:80




