version: '3.1'
services:
  sklearn_api:
    build:
      context: .
    ports:
      - 5000:5000

  tf_api:
      build:
        context: .
        dockerfile: ./Dockerfile.tf
      ports:
        - 5001:5001

  nginx:
      build:
        context: .
        dockerfile: ./Dockerfile.nginx
      depends_on:
        - wsgi
      ports:
        - 80:80

  wsgi:
    build:
      context: .
      dockerfile: ./Dockerfile.wsgi
    ports:
      - 9090:9090

